export const appStrings = {
  loginScreen: {
    welcomeBack: `Welcome back!`,
    loginToContinue: `Login to continue...`,
    forgotPassword: `Forgot Password?`,
    rememberMe: `Remember me`,
    signInBtn: `Sign In`,
    noNetworkLink1: `No Network?`,
    noNetworkLink2: `Use App Offline`,
  },
  forgotPasswordScreen: {
    title: `Forgot Password?`,
    info: `Don’t freak out, help is on the way`,
    resetBtn: `Reset Password`,
    footerLink1: `Suddenly remember it?`,
    footerLink2: ` Login`,
  },
  resetPasswordScreen: {
    title: "Reset Password?",
    info: `Set a new password and be sure to keep it\nsafe this time`,
    setBtn: "Set this Password",
    footerLink1: `Haven't received it?`,
    footerLink2: ` Resend it`,
  },
  homeScreen: {
    goodMorning: `Good morning Emeka!`,
    userType: `Volunteer`,
    assignedLabel: `Assigned`,
    pendingLabel: `Pending`,
    completedLabel: `Completed`,
    assignedValue: `03`,
    pendingValue: `01`,
    completedValue: `02`,
    projectsListHeading: `My Projects`,
  },
  profileScreen: {
    username: `Damian Philpson`,
    myAccount: `My Account`,
    changePassword: `Change Password`,
    helpCenter: `Help Center`,
    logout: `Log Out`,
    backBtn: `Back to dashboard`,
  },
  changePasswordScreen: {
    username: `Damian Philpson`,
    title: `Change Password`,
    info: `Needing to change your password?`,
    submitBtn: `Submit`,
  },
  needHelpScreen: {
    username: `Damian Philpson`,
    title: `Needing Help?`,
    info: `What issues are you facing?`,
    question1: `What is First Child and Prisoner NGO about?`,
    question2: `Do you consider widowers in your programs?`,
    question3: `How do i become a volunteer?`,
    link1: `Still needing help? Contact support`,
    link2: `New FAQ?`,
    backBtn: `Back to Profile`,
  },
  createFAQScreen: {
    username: `Damian Philpson`,
    title: `Create FAQ`,
    info: `Add Frequently Asked Questions to App`,
    submitBtn: `Submit`,
  },
  contactSupportScreen: {
    username: `Damian Philpson`,
    title: `Contact Support`,
    info: `Request help by completig the form`,
    submitBtn: `Submit`,
  },
  notificationsScreen: {
    username: `Damian Philpson`,
    title: `Notifications`,
    info: `Find announcements and  supports here`,
    notifTitle: `What is First Child and Prisoner NGO about?`,
    notifInfo: `Every apartment is a work of art, where no two spaces are the same. Tailored for those with an Every apartment is a work of art, where no two spaces`,
    notifTime: `22 April, 2024 @ 3:00PM`,
    backBtn: `Back`,
  },
  notificationDetailsScreen: {
    username: `Damian Philpson`,
    title: `Notification`,
    info: `To All Volunteers  |  22 April, 2024 @ 3:00PM`,
    notifTitle: `What is First Child and Prisoner NGO about?`,
    notifInfo: `Nam sem arcu, convallis vitae nibh vitae, ultrices lacinia nibh. Phasellus scelerisque bibendum tortor quis tempus. In varius arcu eu mi placerat egestas. Vivamus bibendum ornare orci venenatis hendrerit. Proin placerat, dui sed consequat commodo, nibh diam fermentum erat, at egestas arcu libero non dui. Aliquam rutrum hendrerit fermentum. Aenean neque ligula, molestie a fermentum sed, elementum id turpis. Nam tincidunt tellus ac eros efficitur, vel hendrerit justo vehicula. Vivamus posuere libero vel tristique porttitor. Integer sit amet sodales est.\n\nCras quis velit suscipit, euismod enim vel, varius enim. Mauris imperdiet tellus sapien, et vestibulum sapien ultrices mattis. Nullam eu sapien lacinia, euismod ipsum non, euismod erat. Donec ornare orci imperdiet tincidunt iaculis.\n\nVestibulum at sollicitudin mauris. Quisque sagittis lorem a ligula faucibus, et dignissim libero tincidunt. Nullam erat diam, hendrerit in erat vitae, euismod ultricies ligula. Donec pellentesque faucibus orci quis efficitur. Nunc sed ligula erat. In pretium neque id tortor sodales, ut aliquet metus tempor. Integer posuere lobortis felis et lacinia. Suspendisse gravida tellus eu enim aliquam egestas. Vivamus et orci faucibus, scelerisque ipsum eleifend, semper lectus. Phasellus condimentum consectetur lacus quis eleifend. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis turpis nisi, pellentesque nec ipsum ac, dictum rhoncus justo. Suspendisse convallis, lacus eget lobortis mattis, tortor nulla tincidunt nisl, consectetur feugiat turpis eros et sapien.`,
    backBtn: `Back to Notifications`,
  },
  fileManagerScreen: {
    username: `Damian Philpson`,
    title: `Document Manager`,
    imageListTitle: `Images`,
    videoListTitle: `Videos`,
    fileTitle: `Ojuelegba, somewhere Rivers`,
    fileSize: `2.3kb`,
    fileDateTaken: `23 Oct 2024`,
    backBtn: `Back to dashboard`,
  },
  projectsScreen: {
    offlineDataLabel: `Offline Data`,
    offlineDataValue: `67`,
    clickToUpload: `Click to upload`,
    date: `5 Aug, 2024`,
    location: `NW - Nigeria`,
    beneficiaries: `23 Beneficiaries`,
    programTitle: `This is the Program Title`,
    programInfo: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce a felis non arcu placerat pharetra vel vitae ipsum. Nunc mollis ipsum risus, id scelerisque sapien lacinia vel. Etiam lacinia urna neque, nec semper nisi pellentesque ac. Nulla porta libero quis egestas vehicula. Quisque placerat diam ut nibh facilisis mattis. Nullam molestie nec arcu quis fermentum.\n\nEtiam lacinia urna neque, nec semper nisi pellentesque ac. Nulla porta libero quis egestas vehicula. Quisque placerat diam ut nibh facilisis mattis. Nullam molestie nec arcu quis fermentum.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce a felis non arcu placerat pharetra vel vitae ipsum. Nunc mollis ipsum risus, id scelerisque sapien lacinia vel. Etiam lacinia urna neque, nec semper nisi pellentesque ac.`,
    projectMembers: `Project members`,
    removeLink: `Remove`,
    addBtn: `Add Beneficiaries`,
  },
  projectDetailsScreen: {
    date: `5 Aug, 2024`,
    location: `NW - Nigeria`,
    beneficiariesTitle: "Beneficiaries",
    beneficiaries: `23 Beneficiaries`,
    programTitle: `This is the Program Title`,
    updateLink: `Update`,
    backBtn: `Back to Project`,
  },
  personalInfoScreen: {
    continueBtn: "Contine",
  },
  bottomTabs: {
    home: `Home`,
    projects: `Projects`,
    fileManager: `File Manager`,
    profile: `Profile`,
  },
  labels: {
    emailLabel: "Email/Username",
    passwordLabel: "Password",
    rememberMe: "Remember me",
    pin: "Pin",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    confirmNewPassword: "Confirm New Password",
    faqTitle: `FAQ Title`,
    faqResponse: `FAQ Response`,
    issueType: `Issue Type`,
    to: `To`,
    message: `Message`,
    firstName: "First Name",
    middleName: `Middle Name`,
    lastName: `Last Name`,
    gender: `Gender`,
    dateOfBirth: `Date of birth`,
    address: `Address`,
    phone: `Phone Number`,
    maritalStatus: `Marital Status`,
    nationality: `Nationality`,
    primaryLanguage: `Primary Language`,
    hasDisability: `Has Disability?`,
    typeOfDisability: `Type of disability`,
    fullName: `Full Name`,
    relationship: `Relationship`,
    acquireThumb: `Acquire Thumb`,
    introVideo: `Introductory Video`,
    occupation: `Occupation`,
    income: `Income`,
    houseHoldSize: `Household Size`,
    educationLevel: `Education Level`,
    housingStatus: `Housing Status`,
    vulnerability: `Vulnerability`,
    assistanceRequire: `Type of assistance required`,
    previousAssistance: `Previous assistance received`,
    healthStatus: `Health status`,
    tribe: `Ethnicity/Tribe`,
    religion: `Religion`,
    skills: `Skills & training needed`,
    referOrg: `Referring organization`,
  },
  placeholders: {
    emailPlaceholder: "Type your email/phone",
    passwordPlaceholder: "Type your password",
    provideYourEmailOrUsernmae: "Provide your email or username",
    currenPassword: `Enter your current password`,
    enterNewPassword: "Enter New Password",
    confirmNewPassword: "Confirm New Password",
    setNewPassword: "Set a new password",
    reTypeNewPassword: "Retype new password",
    submitButton: `Submit`,
    faqTitle: `Enter Faq Title`,
    faqResponse: `Enter Faq response...`,
    issueType: `Select Issue`,
    to: `Where you want to send?`,
    message: `Enter Message`,
    firstName: "e.g. Olumide",
    middleName: `e.g. Ahmed `,
    lastName: `e.g. Emeka`,
    gender: `Select Gender`,
    dateOfBirth: `Date of birth`,
    address: `Enter Address`,
    phone: `Phone Number`,
    maritalStatus: `Select`,
    nationality: `Select`,
    primaryLanguage: `Select`,
    hasDisability: `Select`,
    typeOfDisability: `Type of disability`,
    fullName: `Full Name`,
    relationship: `Select`,
    acquireThumb: `Acquire Thumb`,
    introVideo: `Introductory Video`,
    occupation: `e.g Farmer`,
    income: `6,000`,
    houseHoldSize: `Select`,
    educationLevel: `Select`,
    housingStatus: `Select`,
    vulnerability: `Select`,
    assistanceRequire: `e.g Farmer`,
    previousAssistance: `6,000`,
    healthStatus: `Select`,
    tribe: `Select`,
    religion: `Select`,
    skills: `Select`,
    referOrg: ``,
  },
  commonText: {
    noNetwork: "No Network? ",
    useAppOffline: "Use App Offline",
  },
};
